//-- Rich Text Editor functions --
function RT_isAllowed() {
	var sel;
	var obj;
	sel = document.selection
	
	if (sel.type != "Control")
	{
		obj = sel.createRange().parentElement();
	} else {
		obj = sel.createRange()(0);
	}
	
	if (obj.isContentEditable) {
		return obj;
	} else {
		return null;
	}
}

function RT_execCommand(cmd)
{
	var range=RT_isAllowed();
	if (range!=null)
	{
		if (cmd.substring(0,3) == "RT_")
			eval(cmd+"(range);");
		else
			document.execCommand(cmd);
	}
}

// Cleanup code coming from outside (with drag/drop copy/paste, etc.).
// Specially useful for cleaning up code generated by microsoft word.
//
// Removes class and style attributes, xml directive and islands,
// tags with namespaces, empty <p> or span tags.
function RT_cleanup(src) 
{    
	var s = ""+src;
	return s.replace(/<([\w]+) class=([^ |>]*)([^>]*)/gi, "<$1$3"
	).replace(/<([\w]+) style="([^"]*)"([^>]*)/gi, "<$1$3"
	).replace(/<\\?\??xml[^>]>/gi, "").replace(/<\/?\w+:[^>]*>/gi, ""
	).replace(/<p([^>])*>(&nbsp;)*\s*<\/p>/gi,""
	).replace(/<\/?font([^>])*>/gi,""
	).replace(/<span([^>])*>(&nbsp;)*\s*<\/span>/gi,"");
}

// cleanup of html range
function RT_cleanHTML(e)
{
	if (e.innerHTML)
		e.innerHTML = RT_cleanup(e.innerHTML);
}
