{-- deploy images used by the html rich editor --}
{@require:images/Bold.gif:skin}
{@require:images/Copy.gif:skin}
{@require:images/CreateLink.gif:skin}
{@require:images/Cut.gif:skin}
{@require:images/help.gif:skin}
{@require:images/htmledlogo.gif:skin}
{@require:images/Indent.gif:skin}
{@require:images/InsertOrderedList.gif:skin}
{@require:images/InsertUnorderedList.gif:skin}
{@require:images/Italic.gif:skin}
{@require:images/JustifyCenter.gif:skin}
{@require:images/JustifyLeft.gif:skin}
{@require:images/JustifyRight.gif:skin}
{@require:images/Outdent.gif:skin}
{@require:images/Paste.gif:skin}
{@require:images/Redo.gif:skin}
{@require:images/Save.gif:skin}
{@require:images/Separator.gif:skin}
{@require:images/spacer.gif:skin}
{@require:images/StrikeThrough.gif:skin}
{@require:images/SubScript.gif:skin}
{@require:images/SuperScript.gif:skin}
{@require:images/UI_backcolor.gif:skin}
{@require:images/UI_fontcolor.gif:skin}
{@require:images/UI_new.gif:skin}
{@require:images/UI_open.gif:skin}
{@require:images/UI_save_alert.gif:skin}
{@require:images/Underline.gif:skin}
{@require:images/Undo.gif:skin}
{@require:images/Vertical.gif:skin}
{@require:images/RT_cleanHTML.gif}
