<?php

$list = array(
	"?"	=> "manquant ou format incorrect",
	"empty" => "champ non rempli",
	"format" => "format incorrect",
	"missing" => "champ manquant",
	"file too big" => "taille de fichier trop importante (taille max=%1\$d Octets)",
	"invalid file type" => "type de fichier invalid",
	"failed upload" => "erreur de transfert du fichier",
	"not selected" => "non selectionne",
	"invalid number" => "nombre non valide",
	"incorrect" => "valeur incorrecte",
	"incomplete date" => "date incomplete (%1\$s)",
	"invalid date" => "date invalide"
);

?>