<?php $properties["fprops"]=array(
array('name'=>'oid','label'=>'object id','type'=>'text','isKey'=>'primary','show'=>false,'isEdit'=>false,'srcName'=>'oid','ufname'=>'_oid','qname'=>'ds_category_oid','onInput'=>"keypress_number()",'size'=>'8','maxLength'=>'10','multiLines'=>false,),);
$properties["falias"]=array('oid'=>'oid','_oid'=>'oid',);
$properties['frole']=array();
$properties['rprops']=array('name'=>'ds_category.count_branches');
 ?>