<?php

$list = array(
	"?"	=> "field Error",
	"empty" => "empty or invalid field",
	"format" => "bad field format",
	"missing" => "missing field",
	"missing file" => "file missing or empty",
	"file too big" => "file size too big (max limit=%1\$d Bytes )",
	"invalid file type" => "invalid file type",
	"failed upload" => "failed upload",
	"not selected" => "not selected",
	"invalid number" => "invalid number",
	"incorrect" => "incorrect",
	"incomplete date" => "incomplete date (%1\$s)",
	"invalid date" => "invalid date"
);

?>