<?php

$list = array(
	"?"	=> "Erreur de champs",
	"empty" => "le champ vide ou la syntaxe est incorrecte",
	"format" => "la syntaxe du champ incorrecte",
	"missing" => "le champ est manquant",
	"missing file" => "le fichier vide ou inexistant",
	"file too big" => "la taille du fichier est trop importante (taille limite=%1\$d Octets )",
	"invalid file type" => "le type de fichier est non supporté",
	"failed upload" => "l'envoi du fichier a échoué",
	"not selected" => "non sélectionné",
	"invalid number" => "invalid number",
	"incorrect" => "incorrecte",
	"incomplete date" => "date incomplète (%1\$s)",
	"invalid date" => "date invalide"
);

?>