<?php

// form fields handlers
$list = array(
'title'=>'title',
'error'=>'error',
'day'=>'day',
'month'=>'month',
'year'=>'year',
'is not set'=>'is not set',
'invalid date'=>'invalid date',
'error, please check following fields'=>'error, please check following fields',
'invalid date, check'=>'invalid date, check',

// image control
'keep image'=>'keep image',
'replace image'=>'replace image',
'delete image'=>'delete image',
'image database'=>'image database',
'Select...'=>'Select...',
'upload image'=>'upload image',

// file control
'keep file'=>'keep file', 
'replace file'=>'replace file', 
'delete file'=>'delete file', 
'file database'=>'file database', 

 // date
'month' => 'month',
'day'   => 'day',
'year'  => 'year',
'prompt' => 'select',

// phone
'international code'=>'international code',
'local number'=>'local number',
'incomplete phone number'=>'incomplete phone number',
'invalid phone number'=>'invalid phone number',

// list select
'Please select an option'=>'Please select an option',
'Selected values'=>'Selected values',
'Values you can add'=>'Values you can add...',
 

'list help select'=> 'Select an option in right list and click on <strong>"&lt;--"</strong> button to add it to selection.<br/>Select an option in left list and click on <strong>"--&gt;"</strong> button to remove it to selection.</br>Use text box on right side to filter values in right list or add a new value in list.',

// dates
'format_datetime_short' => '%d/%m/%Y at %H:%M',
'format_datetime_long' => '%A %d %B %Y at %H:%M',
'format_datetime_timestamp' => '%A %d %B %Y at %H:%M',
'format_datetime_year' => '%Y',
'format_datetime_vide' => '-/-/-',

'format_date_short' => '%d/%m/%Y',
'format_date_long' => '%A %d %B %Y',
'format_date_timestamp' => '%A %d %B %Y at %H:%M',
'format_date_year' => '%Y',
'format_date_vide' => '-/-/-',

// sous formulaires
'add record' => 'add',
'delete?' => 'delete',
'deleted?' => 'restore ?',

);

?>