<?php

// form fields handlers
$list = array(
'title'=>'titre',
'error'=>'erreur',
'is not set'=>'est vide',
'invalid date'=>'date invalide',
'error, please check following fields'=>'erreur, verifier les champs suivants',
'invalid date, check'=>'date invalide, verifier',

// image control
'keep image'=>'garder image',
'replace image'=>'changer image',
'delete image'=>'detruire image',
'image database'=>'base images',
'Select...'=>'Choisir...',
'upload image'=>'envoi image',

// file control
'keep file'=>'garder fichier', 
'replace file'=>'changer fichier', 
'delete file'=>'détruire fichier', 
'file database'=>'base fichiers', 

 // date
'day'=>'jour',
'month'=>'mois',
'year'=>'annee',
'prompt' => 'choisir',

// phone
'international code'=>'numero international',
'local number'=>'numero local pays',
'incomplete phone number'=>'numero telephone incomplet',
'invalid phone number'=>'numero telephone invalide',
 
// list select
'Please select an option'=>'Vous devez selectionner une option',
'Selected values'=>'Votre selection',
'Values you can add'=>'Autres options...',

'list help select'=> 'Selectionnez une option dans la liste de droite et cliquez sur <strong>"&lt;--"</strong> pour l\'ajouter a votre selection.<br/>Selectionnez une option dans la liste de gauche et cliquez sur <strong>"--&gt;"</strong> pour l\'enlever de votre selection.</br>Utilisez le champ de filtrage à droite pour filtrer la boite de selection.',

// dates
'format_datetime_short' => '%d/%m/%Y &agrave; %H:%M',
'format_datetime_long' => '%A %d %B %Y &agrave; %H:%M',
'format_datetime_timestamp' => '%A %d %B %Y &agrave; %H:%M',
'format_datetime_year' => '%Y',
'format_datetime_vide' => '-/-/-',

'format_date_short' => '%d/%m/%Y',
'format_date_long' => '%A %d %B %Y',
'format_date_timestamp' => '%A %d %B %Y &agrave; %H:%M',
'format_date_year' => '%Y',
'format_date_vide' => '-/-/-',

// sous formulaires
'add record' => 'ajouter',
'delete?' => 'supprimer ?',
'deleted?' => 'supprimé ?',

);

?>