<?php

$list = array(
	'logout' => 'You are no longer logged in.<p>Please click on this button to come back to the public site.',
	'forgotten password prompt' => 'Please enter here your user name and email address. We are going to send you a new password for accessing this site.',
	'unknown account information' => 'The user name and email details you provided do not match any existing account. Please check your user name and password and try again. Alternativelly, you can contact us at user@pecr.com.',
	'password sent' => 'Your password has been sent to your email address. Please keep it safe and sign in from the home page.',
	
	'prohibited page' => 'you havent the permission to access this page'
);

?>