<?php
/*
COPYRIGHT NxFrontier Ltd
www.nxfrontier.com
This code may not be copied, modified or redistributed without the written consent of NxFrontier Limited, UK company number 04462961. 
*/

// list resources
$NxLists = array(
		"strings" => array(
			"en" => array(
				"month" => "month",
				"day"   => "day",
				"year"  => "year",
				"prompt" => "select"
			),
			"fr" => array(
				"month" => "mois",
				"day"   => "jour",
				"year"  => "annee",
				"prompt" => "select"
			)
		),
		"months" => array(
			"en" => array(
				"?" => "Month",
				"1" => "Jan",
				"2" => "Feb",
				"3" => "Mar",
				"4" => "Apr",
				"5" => "May",
				"6" => "Jun",
				"7" => "Jul",
				"8" => "Aug",
				"9" => "Sep",
				"10" => "Oct",
				"11" => "Nov",
				"12" => "Dec"		
			),
			"fr" =>	array(
				"?" => "Mois",
				"1" => "Janvier",
				"2" => "Fevrier",
				"3" => "Mars",
				"4" => "Avril",
				"5" => "Mai",
				"6" => "Juin",
				"7" => "Juillet",
				"8" => "Aout",
				"9" => "Septembre",
				"10" => "Octobre",
				"11" => "Novembre",
				"12" => "Decembre"		
			)
		),

		"FieldErrors" => array(
			"en" => array(
				"?"	=> "field Error",
				"empty" => "empty or invalid field",
				"format" => "bad field format",
				"missing" => "missing field",
				"missing file" => "file missing or empty",
				"file too big" => "file size too big (max limit=%1\$d Bytes )",
				"invalid file type" => "invalid file type",
				"failed upload" => "failed upload",
				"not selected" => "not selected",
				"invalid number" => "invalid number",
				"incorrect" => "incorrect",
				"incomplete date" => "incomplete date (%1\$s)",
				"invalid date" => "invalid date"
			),
			"fr" => array(
				"?"	=> "manquant ou format incorrect",
				"empty" => "champ non rempli",
				"format" => "format incorrect",
				"missing" => "champ manquant",
				"file too big" => "taille de fichier trop importante (taille max=%1\$d Octets)",
				"invalid file type" => "type de fichier invalid",
				"failed upload" => "erreur de transfert du fichier",
				"not selected" => "non selectionne",
				"invalid number" => "nombre non valide",
				"incorrect" => "valeur incorrecte",
				"incomplete date" => "date incomplete (%1\$s)",
				"invalid date" => "date invalide"
			)
		)
);

?>