<?php
$properties = array(
'oid' => '1',
'name' => 'Bleu',
'activation_state' => array(
	'html' => 'Active',
	'value' => '1',
),
'top_menu_bg' => '#2A6BA6',
'top_menu_section_bg' => '#4983B8',
'left_menu_bg' => '#2C323F',
'left_menu_title_col' => '#C1B189',
'left_menu_link_col' => '#eee',
'left_menu_link_bg' => 'transparent',
'left_menu_link_border' => '#A6ABB6',
'left_menu_link_hover_bg' => '#4D576E',
'left_menu_link_hover_col' => '#fff',
'left_menu_link_hover_border' => '#A6ABB6',
'home_jumbotron_bg' => '#fff',
'home_jumbotron_col' => '#666',
'home_jumbotron_title' => 'Ecole de formation',
'home_jumbotron_subtitle' => 'Plateforme de gestion des formations',
'home_jumbotron_image' => '',
'home_jumbotron_image__small' => '',
'home_jumbotron_image__name' => '',
'free_css' => '#main_content #banner.jumbotron {padding-top:10px;padding-bottom:10px;}',

);
?>